language: node_js

node_js:
  - "5.5"
  - "4.2"

script:
  - git config user.email "test@example.com"
  - git config --global user.name "Test User"
  - npm test
  - npm i sidekick
  - sidekick -v
  - sidekick run --ci

notifications:
  email: false
  slack: we-are-sidekick:GeIT5wtuKMLImpFXYHWzIGzI
